### ISSUE TITLE
Want to become a Contributor

### ISSUE THREAD

**Issue by PrakharDoneria** [sahilchouksey/soundrex#3]
I want to become a contributor for this repository thus I want permission to fork it and to add new features, also I can't find the working of the application can you please tell me which file is responsible to make users login and serve music. It would make easy for me then to modify the app. Looking forward for your kind response.

**Comment by sahilchouksey** [comment]
Great to hear you're interested in contributing! For user login and authentication, check out these files 
[Auth Files](https://github.com/sahilchouksey/soundrex/tree/master/src/src/pages/Auth)

We've also made the backend repository public: [Soundrex Backend Repository](https://github.com/sahilchouksey/soundrex-backend)

Feel free to explore, and reach out if you have questions.
